# =======================================================================================================
# This is a script for generating "Extended Data Figure 12"
#
# input:
#       1. RIVER.10CV.out.RData
#          Data generated by running main_RIVER_10CV.R: test posterior probabilities from both genomic
#          annotation model and RIVER with 10 cross-validation
#
# output:
#       1. ExtendedDataFigure12.i.pdf (a, b, c separately)
#       2. ExtendedDataFigure12.out.RData
#          Store all data used and generated by running this script
#
# Note that the final figure was slightly modified by using inkscape for visualization purposes
#
# =======================================================================================================

#!/usr/bin/env Rscript

# Recall required packages
rm(list=ls(all=TRUE))
library(ggplot2)

# Master directory
dir = Sys.getenv('RAREVARDIR')

# Recall required functions



# =========== Load input data
load(file = paste(dir,"/data/RIVER.10CV.out.RData",sep=""))



# =========== Main
# Incorporate test posterior probabilities
data_post_prob <- data.frame(G[,1:2],"pZgivenG"=pred_data[,"pZgivenG"],"pZgivenGE"=pred_data[,"pZgivenGE"],
                             "AbsMed"=apply(E[,4:ncol(E)-1], 1, function(x) abs(median(x, na.rm=TRUE))))
colnames(data_post_prob) <- c("indiv","gene","pZgivenG","pZgivenGE","AbsMed")

tisexps <- cbind(data_post_prob,E[,4:ncol(E)-1])

# Generate adjust p-values based on binomial distributions
tisexps = cbind(tisexps,Ntot=apply(!is.na(tisexps[,6:ncol(tisexps)]),1,sum),Nout=apply(abs(tisexps[,6:ncol(tisexps)]) >= 2,1,sum,na.rm=TRUE))
bin_exp = as.vector(as.matrix(tisexps[,6:ncol(tisexps)-2]))
bin_exp = bin_exp[complete.cases(bin_exp)]
bin_exp = ifelse(abs(bin_exp)>=2,1,0)
emp_prob = sum(bin_exp)/length(bin_exp) # empirical probability for binomial distribution

tisexps = cbind(tisexps,frac_tis=tisexps[,"Nout"]/tisexps[,"Ntot"])
pvalues = data.frame(pval=rep(NA,dim(tisexps)[1]),adjpval=rep(NA,dim(tisexps)[1]))
for (i in 1:dim(tisexps)[1]) {
  pvalues[i,1] = binom.test(sum(abs(tisexps[i,6:ncol(tisexps)]) >= 2,na.rm=TRUE),
                            sum(!is.na(tisexps[i,6:ncol(tisexps)])),emp_prob,alternative = 'g')$p.value
}
pvalues[,2] = p.adjust(pvalues[,1],"fdr") # Benjamini Hochberg FDR adjusted P-value
tisexps = cbind(tisexps,pvalues)

# Search two thresholds (top 5 % and 1 % from both P(FR | G) and P(FR | G, E))
thrds.pZgivenG = c(0,quantile(pred_data[which(tisexps[,"adjpval"]<0.05),"pZgivenG"],c(.95,.99)),1)
names(thrds.pZgivenG) = c("100%","5%","1%","0%")
thrds.pZgivenGE = c(0,quantile(pred_data[which(tisexps[,"adjpval"]<0.05),"pZgivenGE"],c(.95,.99)),1)
names(thrds.pZgivenGE) = c("100%","5%","1%","0%")

data_frac_tis = data.frame(indiv=factor(), gene=factor(), postprob=numeric(), outlier=numeric(), 
                     frac_tis=numeric(), type=factor(), range=factor(), check.names=FALSE)

# Data based on frac_tis & pZgivenG (genomic annotation model)
for (i in 1:(length(thrds.pZgivenG)-1)){
  target_data = tisexps[which((tisexps[,"adjpval"]<0.05) & (tisexps[,"pZgivenG"] >= thrds.pZgivenG[i]) & 
                                (tisexps[,"pZgivenG"] < thrds.pZgivenG[i+1])),c("indiv","gene","pZgivenG","AbsMed","frac_tis")]
  target_data = data.frame(indiv=target_data[,"indiv"],
                           gene=target_data[,"gene"],
                           postprob=target_data[,"pZgivenG"],
                           outlier=ifelse(target_data[,"AbsMed"]>=1.5,1,0),
                           frac_tis=target_data[,"frac_tis"],
                           type=rep("Genomic annotation model\nP(FR | G)",nrow(target_data)),
                           range=rep(paste(names(thrds.pZgivenG)[i]," <= P < ",names(thrds.pZgivenG)[i+1]),nrow(target_data)),
                           check.names=FALSE)
  data_frac_tis = rbind(data_frac_tis,target_data)
}
# Data based on frac_tis & pZgivenGE (RIVER)
for (i in 1:(length(thrds.pZgivenGE)-1)){
  target_data = tisexps[which((tisexps[,"adjpval"]<0.05) & (tisexps[,"pZgivenGE"] >= thrds.pZgivenGE[i]) & 
                                (tisexps[,"pZgivenGE"] < thrds.pZgivenGE[i+1])),c("indiv","gene","pZgivenGE","AbsMed","frac_tis")]
  target_data = data.frame(indiv=target_data[,"indiv"],
                           gene=target_data[,"gene"],
                           postprob=target_data[,"pZgivenGE"],
                           outlier=ifelse(target_data[,"AbsMed"]>=1.5,1,0),
                           frac_tis=target_data[,"frac_tis"],
                           type=rep("RIVER\nP(FR | G, E)",nrow(target_data)),
                           range=rep(paste(names(thrds.pZgivenGE)[i]," <= P < ",names(thrds.pZgivenGE)[i+1]),nrow(target_data)),
                           check.names=FALSE)
  data_frac_tis = rbind(data_frac_tis,target_data)
}

##### Generate figures
colors = c('mediumpurple','dodgerblue')
names(colors) = c('Genomic annotation model\nP(FR | G)', 'RIVER\nP(FR | G, E)')

ggplot(data=data_frac_tis[which(data_frac_tis[,"outlier"]==1),], aes(x = type, y = frac_tis, fill = type, alpha = range)) +
  geom_boxplot(outlier.colour = NA) +
  scale_alpha_discrete(range = c(0.3, 1),
                       name = 'Range of test probabilities', 
                       breaks = c('100%  <= P <  5%','5%  <= P <  1%','1%  <= P <  0%')) +
  theme_bw() + xlab('') + ylab('Fraction of tissues with |Z-score| >= 2') + 
  scale_fill_manual(values = colors, guide = F) +
  scale_y_continuous(limits=c(0,1)) +
  theme(axis.title = element_text(size = 14),
        axis.text.y = element_text(size = 12),
        axis.text.x = element_text(size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(), 
        legend.position = "none")
ggsave(paste(dir,"/paper_figures/ExtendedDataFigure12.a.pdf",sep=""), width=6, height=4.5)

# scatter plots: P(FR | G)
data_pZgivenG = data_frac_tis[which(data_frac_tis[,"type"]=="Genomic annotation model\nP(FR | G)"),]

# Genomic annotation model: outlier
corr_pZgivenG = cor.test(data_frac_tis[which((data_frac_tis[,"type"]=="Genomic annotation model\nP(FR | G)") &
                                               (data_frac_tis[,"outlier"]==1)),"postprob"],
                         data_frac_tis[which((data_frac_tis[,"type"]=="Genomic annotation model\nP(FR | G)") & 
                                               (data_frac_tis[,"outlier"]==1)),"frac_tis"],
                         alternative="two.sided",
                         method="kendall") # corr = 0.122, p-value = 9.85x10-11

# Genomic annotation model: non-outlier
corr_pZgivenG = cor.test(data_frac_tis[which((data_frac_tis[,"type"]=="Genomic annotation model\nP(FR | G)") & 
                                               (data_frac_tis[,"outlier"]==0)),"postprob"],
                         data_frac_tis[which((data_frac_tis[,"type"]=="Genomic annotation model\nP(FR | G)") & 
                                               (data_frac_tis[,"outlier"]==0)),"frac_tis"],
                         alternative="two.sided",
                         method="kendall") # corr = -0.031, p-value = 0.038

ggplot(data_pZgivenG, aes(x = postprob, y = frac_tis)) +
  geom_point(data=data_pZgivenG[which(data_pZgivenG[,"outlier"]==0),], 
             aes(postprob,frac_tis), color="darkgray", alpha=0.5, size=2) +
  geom_point(data=data_pZgivenG[which(data_pZgivenG[,"outlier"]==1),], 
             aes(postprob,frac_tis), color="mediumpurple", alpha=0.25, size=2) +
  theme_bw() + 
  xlab('Genomic annotation model, P(FR | G)') + ylab('Fraction of tissues with |Z-score >= 2|') + 
  scale_y_continuous(limits=c(0.15,1)) +
  # annotate("text", x = .55, y = .05, label = "r = 0.123, P < 8.19 x 10-11", size=5, color="mediumpurple") +
  theme(axis.title = element_text(size = 14),
        axis.text.y = element_text(size = 12),
        axis.text.x = element_text(size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

ggsave(paste(dir,"/paper_figures/ExtendedDataFigure12.b.pdf",sep=""), width=5.5, height=4.5)

# scatter plots: P(FR | G, E)
data_pZgivenGE = data_frac_tis[which(data_frac_tis[,"type"]=="RIVER\nP(FR | G, E)"),]

# RIVER: outlier
corr_pZgivenGE = cor.test(data_frac_tis[which((data_frac_tis[,"type"]=="RIVER\nP(FR | G, E)") & 
                                                (data_frac_tis[,"outlier"]==1)),"postprob"],
                          data_frac_tis[which((data_frac_tis[,"type"]=="RIVER\nP(FR | G, E)") & 
                                                (data_frac_tis[,"outlier"]==1)),"frac_tis"],
                          alternative="two.sided",
                          method="kendall") # corr = 0.121, p-value = 1.92x10-10

# RIVER: non-outlier
corr_pZgivenGE = cor.test(data_frac_tis[which((data_frac_tis[,"type"]=="RIVER\nP(FR | G, E)") & 
                                                (data_frac_tis[,"outlier"]==0)),"postprob"],
                          data_frac_tis[which((data_frac_tis[,"type"]=="RIVER\nP(FR | G, E)") & 
                                                (data_frac_tis[,"outlier"]==0)),"frac_tis"],
                          alternative="two.sided",
                          method="kendall") # corr = -0.027, p-value = 0.068

ggplot(data_pZgivenGE, aes(x = postprob, y = frac_tis)) +
  geom_point(data=data_pZgivenGE[which(data_pZgivenGE[,"outlier"]==0),], aes(postprob,frac_tis), color="darkgray", alpha=0.5, size=2) +
  geom_point(data=data_pZgivenGE[which(data_pZgivenGE[,"outlier"]==1),], aes(postprob,frac_tis), color="dodgerblue", alpha=0.25, size=2) +
  theme_bw() +
  # scale_y_continuous(limits=c(0,1)) +
  #annotate("text", x = .7, y = .05, label = "r = 0.121, P < 1.94 x 10-10", size=5, color="dodgerblue") +
  scale_y_continuous(limits = c(0.15,1)) +
  xlab('RIVER, P(FR | G, E)') + 
  ylab('Fraction of tissues with |Z-score >= 2|') + 
  theme(axis.title = element_text(size = 14),
        axis.text.y = element_text(size = 12),
        axis.text.x = element_text(size = 12),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

ggsave(paste(dir,"/paper_figures/ExtendedDataFigure12.c.pdf",sep=""), width=5.5, height=4.5)



# =========== Save data
save.image(file = paste(dir,"/data/ExtendedDataFigure12.out.RData",sep=""))