# =======================================================================================================
# This is a script for generating "Extended Data Figure 14 (Z-score)"
#
# input:
#       1. figure5c.out.RData
#          Data generated by running figure5.R: importing data associated with ClinVar-matched instances
#       2. gtex_2015-01-12_wgs_ids_outlier_filtered.txt
#          List of GTEx individual IDs (116 European individuals)
#       3. Zscores.ClinVar.subset.txt
#          [six cases matched with ClinVar (regulatory pathogenic variants) x (indiv, gene, symbol, 
#          chr(SNV), pos(SNV), ID(SNV), Disease, P(FR | G), P(FR | G, E), |Median Z-score|, 44 tissues)]
#       4. Zscores.ClinVar.all.txt
#          [all instances associated with genes from the six cases matched with ClinVar x (indiv, gene, 
#          Median Z-score across tissues, 44 tissues)]
#       5. gtex_tissue_colors.txt
#          [Number of tissues x (tissue site detail, tissue site detail abbreviation, tissue site detail ID,
#          tissue site, tissue color in hexadecimal, tissue color in RGB)]
#
# output:
#       1. ExtendedDataFigure14.zscore.i.pdf (a, b separately)
#       2. ExtendedDataFigure14.i.tissue_order.txt: order of tissues in figures (a, b separately)
#       3. ExtendedDataFigure14.zscore.out.RData
#          Store all data used and generated by running this script
#
# Note that the final figure was slightly modified by using inkscape for visualization purposes
#
# =======================================================================================================

#!/usr/bin/env Rscript

# Recall required packages
rm(list=ls(all=TRUE))
library(ggplot2)

# Master directory
dir = Sys.getenv('RAREVARDIR')

# Recall required functions



# =========== Load input data
# load ClinVar-matched data
load(file = paste(dir,"/data/figure5c.out.RData",sep="")) 
# load a list of individual IDs considered here
list_indivs_all = as.character(unlist(read.table(paste(dir,"/reference/gtex_2015-01-12_wgs_ids_outlier_filtered.txt",sep=""),
                                                 sep='\t', header = FALSE, na.strings = "NA"))) 
# load Z-score values of genes for individuals with pathogenic variants
clinvar.zscore = read.table(paste(dir,"/data/Zscores.ClinVar.subset.txt",sep=""),
                            sep='\t', header = TRUE, na.strings = "NA",check.names=FALSE)
colnames(clinvar.zscore)[10] <- "AbsMed"

# load Z-score values of genes for all individuals
clinvar.zscore_bg = read.table(paste(dir,"/data/Zscores.ClinVar.all.txt",sep=""),
                               sep='\t', header = TRUE, na.strings = "NA",check.names=FALSE)
colnames(clinvar.zscore_bg)[3] <- "AbsMed"

table_colors = read.table(paste(dir,"/reference/gtex_tissue_colors.txt",sep=""),
                          sep='\t', header = TRUE, na.strings = "NA")
group_name = c("AA","AB","AC","AD","AE","AF","AG","AH","AI","AJ","AK",
               "BA","BB","BC","BD","BE","BF","BG","BH","BI","BJ","BK",
               "C","D","E","F","G","H","I","J","K","L","M",
               "N","O","P","Q","R","S","T","U","V","W","X","Y","Z")

# =========== Main
## Example 1: SBDS
target_gene = unique(as.character(clinvar.pathoreg[which(clinvar.pathoreg[,"symbol"]=="SBDS"),"gene"]))
idx_samples = which(clinvar.zscore[,"gene"]==target_gene)

# list of observed tissues for the selected samples
obs_tissues = colnames(clinvar.zscore)[setdiff(which(apply(!is.na(clinvar.zscore[idx_samples,]),2,sum,na.rm=TRUE)>0),seq(1,10,1))]
med_diff = data.frame(matrix(NA,2,length(obs_tissues)+1)) # observed tissues + 1 median
colnames(med_diff) = c(obs_tissues,"AbsMed")

count_samples = 0
temp_med_diff = matrix(NA,length(idx_samples),length(obs_tissues)+1) 
for (s in idx_samples) {
  count_samples = count_samples + 1
  for (t in 1:length(obs_tissues)) {
    temp_med_diff[count_samples,t] = clinvar.zscore[s,obs_tissues[t]]
  }
  temp_med_diff[count_samples,length(obs_tissues)+1] = clinvar.zscore[s,"AbsMed"]
}
med_diff[1,] = apply(temp_med_diff,2,mean,na.rm=TRUE)

idx_indiv = which(clinvar.zscore_bg[,"gene"] == target_gene)
exp_mat = data.frame(clinvar.zscore_bg[idx_indiv,4:ncol(clinvar.zscore_bg)],
                     AbsMed=matrix(NA,length(idx_indiv),1),check.names=FALSE) # 44 tissues + 1 median
exp_mat[,"AbsMed"] = apply(exp_mat[,1:ncol(exp_mat)-1],1,median,na.rm=TRUE)
for (t in 1:length(obs_tissues)) {
  med_diff[2,obs_tissues[t]] = median(exp_mat[,obs_tissues[t]],na.rm=TRUE)
}
med_diff[2,ncol(med_diff)] = median(exp_mat[,ncol(exp_mat)],na.rm=TRUE)
metric_med_diff = abs(med_diff[1,1:ncol(med_diff)-1]-med_diff[2,1:ncol(med_diff)-1])
idx_tissues = order(metric_med_diff)

obs_tissues_sorted = c(colnames(metric_med_diff[idx_tissues]),"AbsMed")
labels_readable = vector()
for (i in 1:length(obs_tissues_sorted)-1) {
  labels_readable = c(labels_readable,
                      as.character(table_colors[which(as.character(table_colors[,"tissue_site_detail_id"])==obs_tissues_sorted[i]),"tissue_site_detail"]))
}
labels_readable = c(labels_readable,"Median")
write.table(obs_tissues_sorted, file = paste(dir,"/data/ExtendedDataFigure14.a.tissue_order.txt",sep=""), 
            quote=FALSE, sep="\t", row.names=FALSE, na="NaN");

# data for boxplot (all expression data)
names = vector()
values = vector()
colors = vector()
for (i in 1:length(obs_tissues_sorted)) {
  idx_target_ind = which(is.na(exp_mat[,obs_tissues_sorted[i]]) == FALSE)
  names = c(names,rep(group_name[i],length(idx_target_ind)))
  values = c(values,exp_mat[idx_target_ind,obs_tissues_sorted[i]])
  if (obs_tissues_sorted[i] != "AbsMed") {
    colors = c(colors,rep(paste("#",as.character(table_colors[which(table_colors[,"tissue_site_detail_id"]==obs_tissues_sorted[i]),
                                                              "tissue_color_hex"]),sep=""),length(idx_target_ind)))
  } else {
    colors = c(colors,rep("#FFFFFF",length(idx_target_ind)))
  }
}
names(colors) = names
exp_gene = data.frame(names,values)
data <- exp_gene

# data for point data (sample-specific)
names = vector()
values = vector()
indsnv = vector()
for (s in idx_samples) {
  for (i in 1:length(obs_tissues_sorted)) {
    if (is.na(clinvar.zscore[s,obs_tissues_sorted[i]]) == FALSE) {
      names = c(names,group_name[i])
      values = c(values,clinvar.zscore[s,obs_tissues_sorted[i]])
      indsnv = c(indsnv,paste(as.character(clinvar.pathoreg[s,"indiv"]),
                              as.character(clinvar.pathoreg[s,"ID(SNV)"]),sep=""))
    }
  }
}
data_ind = data.frame(names,values,indsnv)

list_indsnv = unique(indsnv)
ggplot(data=exp_gene, aes(names,values,fill=names))+
  geom_boxplot(outlier.color="gray", outlier.size=1)+
  scale_x_discrete(breaks=group_name[1:length(obs_tissues_sorted)],
                   labels=labels_readable)+
  scale_fill_manual(values=colors)+
  geom_point(data=data_ind[which(data_ind[,"indsnv"]==list_indsnv[1]),],
             aes(names,values),color="darkred",size=1.5,shape=2)+
  geom_point(data=data_ind[which(data_ind[,"indsnv"]==list_indsnv[2]),],
             aes(names,values),color="darkred",size=1.5,shape=6)+
  geom_point(data=data_ind[which(data_ind[,"indsnv"]==list_indsnv[3]),],
             aes(names,values),color="darkred",size=1.5,shape=8)+
  ggtitle("SBDS")+
  coord_flip()+theme_bw()+
  labs(x="Tissues",y="Z-score")+
  guides(fill=FALSE)+
  theme(plot.title = element_text(size = 12),
        axis.title.x = element_text(size=12),
        axis.text.x  = element_text(size=10),
        axis.title.y = element_text(size=12),
        axis.text.y  = element_text(size=10),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

ggsave(paste(dir,"/paper_figures/ExtendedDataFigure14.zscore.a.pdf",sep=""),width=6,height=6.5)

## Example 2: GAMT
target_gene = unique(as.character(clinvar.pathoreg[which(clinvar.pathoreg[,"symbol"]=="GA25"),"gene"]))
idx_samples = which(clinvar.zscore[,"gene"]==target_gene)

# list of observed tissues for the selected samples
obs_tissues = colnames(clinvar.zscore)[setdiff(which(apply(!is.na(clinvar.zscore[idx_samples,]),2,sum,na.rm=TRUE)>0),seq(1,10,1))]
med_diff = data.frame(matrix(NA,2,length(obs_tissues)+1)) # observed tissues + 1 median
colnames(med_diff) = c(obs_tissues,"AbsMed")

count_samples = 0
temp_med_diff = matrix(NA,length(idx_samples),length(obs_tissues)+1) 
for (s in idx_samples) {
  count_samples = count_samples + 1
  for (t in 1:length(obs_tissues)) {
    temp_med_diff[count_samples,t] = clinvar.zscore[s,obs_tissues[t]]
  }
  temp_med_diff[count_samples,length(obs_tissues)+1] = clinvar.zscore[s,"AbsMed"]
}
med_diff[1,] = apply(temp_med_diff,2,mean,na.rm=TRUE)

idx_indiv = which(clinvar.zscore_bg[,"gene"] == target_gene)
exp_mat = data.frame(clinvar.zscore_bg[idx_indiv,4:ncol(clinvar.zscore_bg)],
                     AbsMed=matrix(NA,length(idx_indiv),1),check.names=FALSE) # 44 tissues + 1 median
exp_mat[,"AbsMed"] = apply(exp_mat[,1:ncol(exp_mat)-1],1,median,na.rm=TRUE)
for (t in 1:length(obs_tissues)) {
  med_diff[2,obs_tissues[t]] = median(exp_mat[,obs_tissues[t]],na.rm=TRUE)
}
med_diff[2,ncol(med_diff)] = median(exp_mat[,ncol(exp_mat)],na.rm=TRUE)
metric_med_diff = abs(med_diff[1,1:ncol(med_diff)-1]-med_diff[2,1:ncol(med_diff)-1])
idx_tissues = order(metric_med_diff)

obs_tissues_sorted = c(colnames(metric_med_diff[idx_tissues]),"AbsMed")
labels_readable = vector()
for (i in 1:length(obs_tissues_sorted)-1) {
  labels_readable = c(labels_readable,
                      as.character(table_colors[which(as.character(table_colors[,"tissue_site_detail_id"])==obs_tissues_sorted[i]),"tissue_site_detail"]))
}
labels_readable = c(labels_readable,"Median")
write.table(obs_tissues_sorted, file = paste(dir,"/data/ExtendedDataFigure14.b.tissue_order.txt",sep=""), 
            quote=FALSE, sep="\t", row.names=FALSE, na="NaN");

# data for boxplot (all expression data)
names = vector()
values = vector()
colors = vector()
for (i in 1:length(obs_tissues_sorted)) {
  idx_target_ind = which(is.na(exp_mat[,obs_tissues_sorted[i]]) == FALSE)
  names = c(names,rep(group_name[i],length(idx_target_ind)))
  values = c(values,exp_mat[idx_target_ind,obs_tissues_sorted[i]])
  if (obs_tissues_sorted[i] != "AbsMed") {
    colors = c(colors,rep(paste("#",as.character(table_colors[which(table_colors[,"tissue_site_detail_id"]==obs_tissues_sorted[i]),
                                                              "tissue_color_hex"]),sep=""),length(idx_target_ind)))
  } else {
    colors = c(colors,rep("#FFFFFF",length(idx_target_ind)))
  }
}
names(colors) = names
exp_gene = data.frame(names,values)
data <- exp_gene

# data for point data (sample-specific)
names = vector()
values = vector()
snvs = vector()
for (s in idx_samples) {
  for (i in 1:length(obs_tissues_sorted)) {
    if (is.na(clinvar.zscore[s,obs_tissues_sorted[i]]) == FALSE) {
      names = c(names,group_name[i])
      values = c(values,clinvar.zscore[s,obs_tissues_sorted[i]])
      snvs = c(snvs,as.character(clinvar.pathoreg[s,"ID(SNV)"]))
    }
  }
}
data_ind = data.frame(names,values,snvs)

list_snvs = unique(as.character(clinvar.pathoreg[idx_samples,"ID(SNV)"]))
ggplot(data=exp_gene, aes(names,values,fill=names))+
  geom_boxplot(outlier.color="gray", outlier.size=1)+
  scale_x_discrete(breaks=group_name[1:length(obs_tissues_sorted)],
                   labels=labels_readable)+
  scale_fill_manual(values=colors)+
  geom_point(data=data_ind[which(data_ind[,"snvs"]==list_snvs[1]),],
             aes(names,values),color="darkred",size=1.5,shape=8)+
  ggtitle("GAMT")+ coord_flip()+ theme_bw()+
  labs(x="Tissues",y="Z-score")+
  guides(fill=FALSE)+
  theme(plot.title = element_text(size = 12),
        axis.title.x = element_text(size=12),
        axis.text.x  = element_text(size=10),
        axis.title.y = element_text(size=12),
        axis.text.y  = element_text(size=10),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank())

ggsave(paste(dir,"/paper_figures/ExtendedDataFigure14.zscore.b.pdf",sep=""),width=6,height=2.5)



# =========== Save data
save.image(file = paste(dir,"/data/ExtendedDataFigure14.zscore.out.RData",sep=""))