# ===================================================================================================================
# This is a script for generating the data for Extended Data Table 4
# input:
#       1. RIVER.out.RData
#          Data generated by running main_RIVER.R
# ===================================================================================================================

# Load required packages

# Master directory
dir = Sys.getenv('RAREVARDIR')

# Recall required functions



# =========== Load input data
load(file = paste(dir,"/data/RIVER.out.RData",sep=""))



# =========== Main
target.features = c("max_DANN_10kb","max_PHRED_10kb","max_TFBS_10kb","max_verPhyloP_10kb")
target.labels = c("DANN","CADD","logistic","PhyloP(Ver)","TFBS","EXP")

x_sub = cbind(G[dups[,1],target.features[1:2]],pp[dups[,1]],G[dups[,1],target.features[3:4]],E_disc[dups[,1]])
colnames(x_sub) <- target.labels;
y_sub = E_disc[dups[,2]]

x <- c(1:(ncol(x_sub)-1))
y <- seq(1,5,by=1)
xlow <-c(1:(ncol(x_sub)-1))
xup <-c(1:(ncol(x_sub)-1))
cond <- c("A","A","B","C","C")
n <- c(1:(ncol(x_sub)-1))

for (i in 1:(ncol(x_sub)-1)) {
  features <- data.frame(y=y_sub, x1=x_sub[,i], x2=x_sub[,ncol(x_sub)])
  model <- glm(y ~ x1 + x2, data = features, family = "binomial") # logistic regression model with two variables
  x[i] <- round(model$coefficients[3],2)
  n[i] <- paste("p < ",as.character(summary(model)$coefficients[3, "Pr(>|z|)"]),sep="")
  confint <- confint(model)
  xlow[i] <- round(confint[3,1],2)
  xup[i] <- round(confint[3,2],2)
}