# =======================================================================================================
# This is a script for generating "Extended Data Figure 3"
#
# input:
#       1. zscore_statistics.txt: Spearman rank correlations between |Z-score| from 5th tissue and 
#          multi-tissue outlier status from four tissues (first three columns) and their -log10(P-values) 
#          (next three columns) baesd on three different thresholds of calling multi-tissue outliers [2, 3, 4].
#          [# of trials for selecting five tissues from 27 tissues having at least 100 European individuals
#           x (correlation with threshold 2, correlation with threshold 3, correlation with threshold 4, 
#           P-value with threshold 2, P-value with threshold 3, P-value with threshold 4)]
#       2. rpkm_statistics.txt: Spearman rank correlations between |Z-transformed RPKM values| from 5th 
#          tissue and multi-tissue outlier status from four tissues (first three columns) and their 
#          -log10(P-values) (next three columns) baesd on three different thresholds of calling multi-tissue 
#          outliers [2, 3, 4].
#          [# of trials for selecting five tissues from 27 tissues having at least 100 European individuals
#           x (correlation with threshold 2, correlation with threshold 3, correlation with threshold 4, 
#           P-value with threshold 2, P-value with threshold 3, P-value with threshold 4)]
#
# output:
#       1. ExtendedDataFigure3.pdf 
#       2. ExtendedDataFigure3.out.RData
#          Store all data used and generated by running this script
#
# Note that the final figure was generated by using inkscape by combining figures from this script for visualization purposes
#
# =======================================================================================================

#!/usr/bin/env Rscript

# Recall required packages
rm(list=ls(all=TRUE))

# Master directory
dir = Sys.getenv('RAREVARDIR')

# Recall required functions
source("getPlots.R") # this code should be in the same directory as the directory for this script



# =========== Load input data
# rank correlation of |Z-score| from K+1 tissue and multi-tissue outlier status from K tissues (K=4)
zscore_stats = read.table(paste(dir,"/data/zscore_statistics.txt",sep=""), 
                          sep='\t', header = TRUE, check.names=FALSE, na.strings = "NaN", row.names=NULL) 
zscore_stats = zscore_stats[,1:(ncol(zscore_stats)-1)]
zscore_stats = as.matrix(zscore_stats)
class(zscore_stats) <- "numeric"

# rank correlation of |Z-transformed RPKM values| from K+1 tissue and multi-tissue outlier status from K tissues (K=4)
rpkm_stats = read.table(paste(dir,"/data/rpkm_statistics.txt",sep=""),
                          sep='\t', header = TRUE, check.names=FALSE, na.strings = "NaN", row.names=NULL) 
rpkm_stats = rpkm_stats[,1:(ncol(rpkm_stats)-1)]
rpkm_stats = as.matrix(rpkm_stats)
class(rpkm_stats) <- "numeric"



# =========== Main
data_hfc = data.frame(value=numeric(), type=factor(), metric=factor(), thrd=factor(), check.names=FALSE)

# Z-transformed RPKM data
for (i in 1:3){
  target_data = data.frame(value=rpkm_stats[,i],
                           type=rep("Raw",nrow(rpkm_stats)),
                           metric=rep("Rank correlation",nrow(rpkm_stats)),
                           thrd=as.factor(rep(i+1,nrow(rpkm_stats))),
                           check.names=FALSE) # Spearman rank correlation
  data_hfc = rbind(data_hfc,target_data)
  
  target_data = data.frame(value=rpkm_stats[,i+3],
                           type=rep("Raw",nrow(rpkm_stats)),
                           metric=rep("-log10(P)",nrow(rpkm_stats)),
                           thrd=as.factor(rep(i+1,nrow(rpkm_stats))),
                           check.names=FALSE) # -log10(P-values)
  data_hfc = rbind(data_hfc,target_data)
}

# Z-scores from PEER-corrected data
for (i in 1:3){
  target_data = data.frame(value=zscore_stats[,i],
                           type=rep("PEER-corrected",nrow(zscore_stats)),
                           metric=rep("Rank correlation",nrow(zscore_stats)),
                           thrd=as.factor(rep(i+1,nrow(zscore_stats))),
                           check.names=FALSE) # Spearman rank correlation
  data_hfc = rbind(data_hfc,target_data)
  
  target_data = data.frame(value=zscore_stats[,i+3],
                           type=rep("PEER-corrected",nrow(zscore_stats)),
                           metric=rep("-log10(P)",nrow(zscore_stats)),
                           thrd=as.factor(rep(i+1,nrow(zscore_stats))),
                           check.names=FALSE) # -log10(P-values)
  data_hfc = rbind(data_hfc,target_data)
}

colors = c('darkgray','dodgerblue3')
names(colors) = c('Raw', 'PEER-corrected')

getMultipleBoxPlotsGradients(data_hfc[which(data_hfc[,"metric"]=="Rank correlation"),]) # Extended Data Figure 3

ggsave(paste(dir,"/paper_figures/ExtendedDataFigure3.pdf",sep=""), width=6, height=4.5)



# =========== Save data
save.image(file = paste(dir,"/data/ExtendedDataFigure3.out.RData",sep=""))