# =======================================================================================================
# This is a script for generating "figure 5c"
#
# input:
#       1. postprobs_all.txt: a list of posterior probabilities of all instances used for RIVER
#          [# of instances x (indiv, gene, P(FR | G), P(FR | G, E), |Median Z-score|)]
#       2. clinvar_final.table.curated.txt: a list of disease SNVs matched to ClinVar
#          [# of matched cases with clinvar x (Indiv, gene, symbol, chr(SNV), pos(SNV), ID(SNV), 
#           Disease, P(FR | G), P(FR | G, E), |Median Z-score|, Pathogenicity, Molecular consequences)]
#
# output:
#       1. figure 5c.pdf (main, histogram for x-axis, y-axis, and z-axis)
#       2. figure5c.out.RData
#          Store all data used and generated by running this script
#
# Note that the final figure was generated by using inkscape by combining figures from this script for visualization purposes
#
# =======================================================================================================

#!/usr/bin/env Rscript

# Recall required packages
rm(list=ls(all=TRUE))

# Master directory
dir = Sys.getenv('RAREVARDIR')

# Recall required functions
source("getPlots.R") # this code should be in the same directory as the directory for this script



# =========== Load input data
postprobs = read.table(paste(dir,"/data/postprobs_all.txt",sep=""), 
                       sep="\t", header=TRUE, na.strings="NaN", check.names=FALSE);
# List of posterior probabilities for all instances from RIVER by running getPosteriorsApp.R (https://github.com/ipw012/RIVER)
clinvar.curated = read.table(paste(dir,"/data/clinvar_final.table.curated.txt",sep=""), 
                             sep="\t", header=TRUE, na.strings="NaN", check.names=FALSE); # List of disease SNVs



# =========== Main
# Extract only pathogenic SNVs
clinvar.pathogenic = clinvar.curated[union(grep(glob2rx("*pathogenic*"),clinvar.curated[,"Clinical significance"]),
                                           grep(glob2rx("*risk*"),clinvar.curated[,"Clinical significance"])),] 

# Check properties of pathogenic SNVs
clinvar.list_diseases = list()
for (i in 1:dim(clinvar.pathogenic)[1]) {
  disease_name = unlist(strsplit(as.character(clinvar.pathogenic[i,"Disease"]),"&"))
  for (j in 1:length(disease_name)) {
    clinvar.list_diseases = append(clinvar.list_diseases,disease_name[j])
  }
}
clinvar.list_diseases = unlist(unique(clinvar.list_diseases))
clinvar.list_indivs = unique(clinvar.pathogenic[,"indiv"])
clinvar.list_genes = unique(clinvar.pathogenic[,"symbol"])
clinvar.list_snps = unique(clinvar.pathogenic[,"ID(SNV)"])

# Check significance of difference between distributions from all instances and pathogenic SNVs
wilcox.test(postprobs[,"pZgivenG"],clinvar.pathogenic[,"pZgivenG"])$p.value
wilcox.test(postprobs[,"pZgivenGE"],clinvar.pathogenic[,"pZgivenGE"])$p.value
wilcox.test(postprobs[,"AbsMed"],clinvar.pathogenic[,"AbsMed"])$p.value

# Selection of only regulatory pathogenic SNVs 
clinvar.pathoreg = 
  clinvar.pathogenic[setdiff(1:nrow(clinvar.pathogenic),
                             union(grep(glob2rx("*missense*"),clinvar.pathogenic[,"Molecular consequences"]),                                           
                                   grep(glob2rx("*inframe*"),clinvar.pathogenic[,"Molecular consequences"]))),] 



# =========== Generate figures
# figure 5c: main
pdf(paste(dir,"/paper_figures/figure5c.main.pdf",sep=""),useDingbats=FALSE, width=7, height=7)
par(mar=c(6.1, 6.1, 4.1, 4.1))
getPostProbs(postprobs[,"AbsMed"], postprobs[,"pZgivenG"], postprobs[,"pZgivenGE"])
getScatterExmpls(clinvar.pathogenic[,"AbsMed"], clinvar.pathogenic[,"pZgivenG"], "darkorange2")
getScatterExmpls(clinvar.pathoreg[,"AbsMed"], clinvar.pathoreg[,"pZgivenG"], "firebrick")
dev.off()

# figure 5c: x-axis histogram
pdf(paste(dir,"/paper_figures/figure5c.histx.pdf",sep=""),useDingbats=FALSE, width=6, height=2)
par(mar=c(6.1, 6.1, 4.1, 4.1))
dat = rbind(data.frame(x=postprobs[,"AbsMed"], group="A"), # background 
            data.frame(x=clinvar.pathogenic[,"AbsMed"], group="B"), # pathogenic 
            data.frame(x=clinvar.pathoreg[,"AbsMed"], group="C")) # pathogenic + regulatory
getHistExmpls(dat, seq(0,12,.2))
dev.off()

# figure 5c: y-axis histogram
pdf(paste(dir,"/paper_figures/figure5c.histy.pdf",sep=""),useDingbats=FALSE, width=5, height=6)
par(mar=c(6.1, 6.1, 4.1, 4.1))
dat = rbind(data.frame(x=postprobs[,"pZgivenG"], group="A"), # background 
            data.frame(x=clinvar.pathogenic[,"pZgivenG"], group="B"), # pathogenic 
            data.frame(x=clinvar.pathoreg[,"pZgivenG"], group="C")) # pathogenic + regulatory
getHistExmpls(dat, seq(0,0.8,.02))+coord_flip()
dev.off()



# =========== Save data
save.image(file = paste(dir,"/data/figure5c.out.RData",sep=""))
