# ===================================================================================================================
# This is a script for generating "figure 5b"
#
# input:
#       1. RIVER.out.RData
#          Data generated by running main_RIVER.R
#
# output:
#       1. figure5b.pdf
#       2. figure5b.out.RData
#          Store all data used and generated by running this script
#
# Note that the final figure was slightly modified by using inkscape for visualization purposes
#
# ===================================================================================================================

#!/usr/bin/env Rscript

# Recall required packages

# Master directory
dir = Sys.getenv('RAREVARDIR')

# Recall required functions



# =========== Load input data
load(file = paste(dir,"/data/RIVER.out.RData",sep="")) # generated by running getPosteriorsEval.R (https://github.com/ipw012/RIVER)



# =========== Main
# Generate figure 5b: ROC curves of both genomic annotation model and RIVER: 3.5 x 10-4
pdf(paste(dir,"/paper_figures/figure5b.pdf",sep=""),useDingbats=FALSE, width=7, height=7)
par(mar=c(6.1, 6.1, 4.1, 4.1))
plot(NULL,xlim=c(0,1),ylim=c(0,1),xlab="False positive rate",ylab="True positive rate", cex.axis=1.3, cex.lab=1.6)
abline(0, 1, col="gray") 
lines(1-int.em.roc$specificities,int.em.roc$sensitivities, type="s", col='dodgerblue', lwd=4)
lines(1-g.roc$specificities,g.roc$sensitivities, type="s", col='mediumpurple', lwd=4)
legend(0.3,0.2,c("Integrated model","Genomic annotation model"), lty=c(1,1), lwd=c(4,4), 
       col=c("dodgerblue","mediumpurple"), cex=1.2, pt.cex=1.4, bty="n")
dev.off()

# Check significance of difference between AUCs from two models: auc(RIVER) = 0.638, auc(GAM) = 0.541
roc.test(int.em.roc, g.roc)$p.value



# =========== Save data
save.image(file = paste(dir,"/data/figure5b.out.RData",sep=""))