#!/usr/bin/env Rscript

# Load required packages
require(ggplot2)

### Master directory
dir = Sys.getenv('RAREVARDIR')

# Load data generated by call_outliers/multi_tissue_replication.R
load(paste0(dir, '/data/figure1c.replication.rate.consistent.RData'))

# To make the plot look nice and align each observed box with it's background
thresh = paste(replication.thresholds[1])
replication$SIZE = ifelse(replication$THRESH == thresh, replication$SIZE - 0.4, replication$SIZE + 0.4)

# To make legend with the 4 colours
replication$color = paste(replication$Type, replication$THRESH, sep = "_")
rep.colors = c('dodgerblue3', 'grey45', alpha('dodgerblue3', 0.4), alpha('grey45', 0.4))
names(rep.colors) = c('Observed_2', 'Background_2', 'Observed_1', 'Background_1')
color.breaks = c('Observed_1','Observed_2','Background_1','Background_2')
color.labels = c(expression('Observed, |Median Z-score| '<= 1),
                 expression('Observed, |Median Z-score| '<=2),
                 expression('Background, |Median Z-score| '<=1),
                 expression('Background, |Median Z-score| '<=2))

# Common axis font sizes
fontsize = 13
axisFontSizes = theme(axis.text = element_text(size = fontsize - 1), axis.title = element_text(size = fontsize))

# Make the replication plot

pdf(paste0(dir, '/paper_figures/figure1c.replication.rate.consistent.pdf'), width = 4.3, height = 2.8)

replication.plot = ggplot(data = replication, aes(x = SIZE, y = NUM / DEN, group = interaction(SIZE, Type))) + theme_bw() +
	geom_dotplot(aes(fill = color, colour = color),
                     binaxis = 'y', stackdir = 'center', binwidth = .01, dotsize = 2, stackratio = 0.7) + 
	stat_summary(fun.y = median, fun.ymin = median, fun.ymax = median, geom = 'crossbar', width = 1) +
	xlab('Number of tissues in discovery set') + ylab('Replication rate') + 
	scale_colour_manual(values = rep.colors, breaks = color.breaks, labels = color.labels) +
        scale_fill_manual(values = rep.colors, breaks= color.breaks,labels = color.labels) +
	theme(legend.text = element_text(size = fontsize - 3),
              legend.title = element_blank(),
              legend.position = c(0.27, 0.85),
              legend.key = element_blank(),
              legend.key.height = unit(0.8, "line"),
              legend.background = element_blank(), 
              panel.grid.major = element_blank(),
              panel.grid.minor = element_blank()) +
	axisFontSizes + guides(colour = FALSE, fill = FALSE)
replication.plot

dev.off()
