# =======================================================================================================
# This is a script of last step for generating EDF1b.
#
# input:
#       1. cov_for_heatmap.txt
#          a list of names for both sample and subject covariates available
#       2. superheat.x.RData (x: either sample or subject)
#          ajusted R-squared valuesin each tissue generated by process_results.R
# output:
#       a final EDF1b figure
#
# Note that the final figure was slightly modified by using inkscape for visualization purposes
#
# =======================================================================================================

# !/usr/bin/env Rscript

# Recall required packages
rm(list=ls(all=TRUE))

# Master directory
dir = Sys.getenv('RAREVARDIR')

# Recall required functions
library(gplots)

inputargs <- commandArgs(TRUE)
inputfn <- inputargs[1]
savefn <- inputargs[2]
maxval <- as.numeric(inputargs[3])
print(maxval)
load(inputfn)

print(paste(max(tmp.super, na.rm = T)))
print(paste(min(tmp.super, na.rm = T)))
cov.names <- read.delim("/data/cov_for_heatmap.txt",sep = "\t", row.names =1)

pdf(savefn, height = 13, width = 15, useDingbats = F)
tmp.super <- data.frame(t(tmp.super))
keep <- which(sapply(tmp.super,function(x) length(which(is.na(x)))) < 13)
tmp.super <- tmp.super[,keep]
tmp.super[tmp.super < 0.0 ] <- 0.0
tmp.super <- t(tmp.super[,rev(names(sort(sapply(tmp.super, function(p) mean(p, na.rm = T)))))[1:20]])
cov.names <- cov.names[which(cov.names$V1 %in% rownames(tmp.super)),]
rownames(cov.names) <- cov.names$V1
cov.names <- cov.names[rownames(tmp.super),]
rownames(tmp.super) <- cov.names$V2
print(paste(max(tmp.super, na.rm = T)))
print(paste(min(tmp.super, na.rm = T)))

heatmap.2(as.matrix(tmp.super), col = colorRampPalette(RColorBrewer::brewer.pal(6,"RdPu"))(40),
	scale="none",
          margins=c(8,8), # ("margin.Y", "margin.X")
          trace='none', 
          symkey=FALSE, 
          symbreaks=FALSE, 
          dendrogram='none',
          density.info='none', 
          denscol="black",
	  breaks = seq(0, maxval, length.out = 41),
         # cexRow = 1.4,
	  keysize=0.3, 
          key.xlab="",
	  #( "bottom.margin", "left.margin", "top.margin", "left.margin" )
          key.par=list(mar=c(3,0,5,6.5)),
	  key.title = "",
	  # lmat -- added 2 lattice sections (5 and 6) for padding
          lmat=rbind(c(7,8,9),c(5,1,2), c(6, 4, 3)), lhei=c(0.5,3.5, 0.5), lwid=c(0.5, 6, 1)
)
dev.off()
