#!/usr/bin/env Rscript

library(ggplot2)
library(cowplot)

### Master directory
dir = Sys.getenv('RAREVARDIR')

# make supplementary figure that looks at the number of single-tissue outliers that overlap with multi-tissue ones
# and compares that to the sample size in that tissue

# load data generated by call_outliers/compare_single_multi_tissue_outliers.R
load(paste0(dir, '/data/suppfig.single.multi.overlap.RData'))
load(paste0(dir, '/data/figure1b.outlier.sharing.RData'))

fontsize = 10
fontsizes = theme(panel.grid.major = element_blank(),
                  panel.grid.minor = element_blank(),
                  axis.text = element_text(size = fontsize),
                  legend.text = element_text(size = fontsize - 1),
                  axis.title = element_text(size = fontsize),
                  legend.title = element_text(size = fontsize - 1))

# process tissue colors as necessary
tis.colors = paste0("#", tissues$tissue_color_hex)
names(tis.colors) = tissues$tissue_site_detail_id
names(tis.colors)[names(tis.colors) == "Cells_EBV_transformed_lymphocytes"] = "Cells_EBV-transformed_lymphocytes"

single2multi.plot = ggplot(samples.tissue.overlap, aes(x = nsamples, y = prop, colour = TISSUE)) + geom_point() +
    theme_bw() + ylab('Proportion of single-tissue outliers\nthat are multi-tissue outliers') +
    xlab('Number of samples') + guides(colour = FALSE) +
    scale_colour_manual(values = tis.colors) + fontsizes +
    annotate("text", x = 110, y = 0.055, label = paste("Pearson r =", signif(correlation$estimate,3)), size = 3.5)

heatmap.subset = plots70[[1]]
heatmap.subset.subsample = plots70[[2]] + theme(legend.text = element_text(size = fontsize - 1),
                                                legend.title = element_text(size = fontsize - 1))
scatter.discovery.v.all = plots70[[3]] + fontsizes
scatter.discovery.v.distinct = plots70.same.diff[[5]] + fontsizes

white.rectangle = ggplot(data.frame(X = 1, Y = 1)) + geom_point(aes(X, Y)) + xlim(c(0,1)) + ylim(c(0,1)) +
    theme(axis.text = element_text(size = 0),
          axis.title = element_text(size = 0),
          axis.line = element_line(linetype = 0),
          axis.ticks = element_blank(),
          panel.background = element_rect(fill = 'white'))

dots.w = 0.1
heat.w = 0.505
heat.h = 0.335
heat1.x = 0.04
heat2.x = 0.49
scatter.w = 0.4
scatter.h = 0.3
heat.y = 2*scatter.h + 0.02
vert.y = heat.y - 0.039
vert.h = heat.h + 0.07
combined.supp = ggdraw() +
    draw_plot(colors.vertical, heat1.x-0.07, vert.y, dots.w, vert.h) +
    draw_text('Discovery in all individuals', 0.01, 0.79, size = fontsize, angle = 90) +
    draw_plot(colors.horizontal, heat1.x-0.045, 0.915, 0.470, dots.w) +
    draw_text('Replication in all individuals', heat1.x+0.2, 0.99, size = fontsize) +
    draw_plot(heatmap.subset, heat1.x, heat.y, heat.w, heat.h) +
    draw_plot(white.rectangle, heat1.x+0.38, 0.68, 0.2, 0.2) +
    draw_plot(colors.vertical, heat2.x-0.07, vert.y, dots.w, vert.h) +
    draw_text('Discovery in 70 individuals', heat2.x-0.03, 0.79, size = fontsize, angle = 90) +
    draw_plot(colors.horizontal, heat2.x-0.045, 0.915, 0.4835, dots.w) +
    draw_text('Replication in discovery individuals', heat2.x+0.23, 0.99, size = fontsize) +
    draw_plot(heatmap.subset.subsample, heat2.x, heat.y, heat.w, heat.h) +
    draw_plot(scatter.discovery.v.all, (1-scatter.w*2)/2, scatter.h, scatter.w, scatter.h) +
    draw_plot(scatter.discovery.v.distinct, 0.5, scatter.h, scatter.w, scatter.h) +
    draw_plot(single2multi.plot, 0.25, 0, 0.5, scatter.h) +
    draw_plot_label(c('a','b','c','d','e'),
                    c(0, heat2.x-0.04, (1-scatter.w*2)/2 + 0.005, 0.505, 0.252),
                    c(rep(1,2), rep(scatter.h*2, 2), scatter.h), size = 11)
pdf(paste0(dir, '/paper_figures/suppfig.single.replication.multi.overlap.pdf'), height = 11, width = 9)
combined.supp
dev.off()

